//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MircServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MIRCSERVER_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_IPADDRESS                   1000
#define IDC_LISTEN                      1001
#define IDC_EXIT                        1002
#define IDC_SOCKET                      1005
#define IDC_CLIENTNAMESLIST             1006
#define IDC_CLIENTIPADDRESSESLIST       1007
#define IDC_MESSAGES                    1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
